### ISSUE TITLE
Example to use scrapper only

### ISSUE THREAD

**Issue by sabatale** [Robokishan/Crunchy#9]
Do you have any example to use the scrapper independently?

E.g., [https://www.crunchbase.com/organization/anthropic/investor_financials](https://www.crunchbase.com/organization/anthropic/investor_financials)

**Comment by Robokishan** [comment]
Scrapper is just subscribed to queue so if you have some other client pushing to queue it will start consuming. 
scrapper is designed to work independently.

**Comment by Robokishan** [comment]
yeah you will just need to insert one class to scrap this page. and it will work. but yeah you will need to refactor somethings to get it work. but the architecture for this project is designed in a way that scrapper works independently

**Comment by Robokishan** [comment]
@sabatale main problem will be financial data is no longer available publicly on crunchbase. you required account. and then also there is some limit after it.
